<?php

/**
 * @file
 * User dashboard Module
 */

/**
 * Set default dashboard block and permission constant for view.
 */

define('USER_DASHBOARD_PERM_SET_DEFAULT', 'set default user_dashboard blocks');
define('USER_DASHBOARD_PERM_VIEW_ALL',    "view all users' dashboards");

/************************************************************************************
 *                  DRUPAL HOOKS
 ***********************************************************************************/

/**
 * Implements hook_menu().
 */
function user_dashboard_menu() {

  // Shortcut to dashboard
  $items['user/dashboard'] = array(
    'title'             => 'Dashboard',
    'description'       => 'View and customize your dashboard.',
    'page callback'     => 'user_dashboard_page_redirect',
    'access callback'   => '_user_dashboard_access',
    'type'              => MENU_CALLBACK,
  );

  // Main dashboard page
  $items['user/%user/dashboard'] = array(
    'title'             => 'Customize',
    'description'       => 'View and customize your dashboard.',
    'page callback'     => 'user_dashboard_page',
    'access callback'   => '_user_dashboard_access',
    'access arguments'  => array(1),
    'type'              => MENU_LOCAL_TASK,
    'weight'            => 100,
  );

  // Block customization page
  $items['user/%user/dashboard/customize'] = array(
    'title'             => 'Customize dashboard',
    'description'       => 'Customize your dashboard.',
    'page callback'     => 'user_dashboard_page',
    'page arguments'    => array(TRUE),
    'access callback'   => '_user_dashboard_access',
    'type'              => MENU_VISIBLE_IN_BREADCRUMB,
  );

  // Shows disabled blocks in the dashboard config
  $items['user/%user/dashboard/drawer'] = array(
    'page callback'     => 'user_dashboard_show_disabled',
    'access callback'   => '_user_dashboard_access',
    'access callback'   => '_user_dashboard_access',
    'type'              => MENU_CALLBACK,
  );

  // Configuration page
  $items['admin/dashboard/user_dashboard/settings'] = array(
    'title'             => 'User Dashboard Settings',
    'description'       => 'Configure user dashboard settings.',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('user_dashboard_settings'),
    'access arguments'  => array('administer blocks'),
    'type'              => MENU_VISIBLE_IN_BREADCRUMB,
  );

  $items['admin/dashboard-settings'] = array(
    'title'             => 'User Dashboard Settings',
    'description'       => 'Configure user dashboard settings.',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('user_dashboard_settings'),
    'access arguments'  => array('administer blocks'),
    'type'              => MENU_NORMAL_ITEM,
  );

  // Ajax callback for when a block is placed into a region
  $items['user/%user/dashboard/block-content/%/%'] = array(
    'page callback'     => 'user_dashboard_show_block_content',
    'page arguments'    => array(4, 5),
    'access callback'   => '_user_dashboard_access',
    'type'              => MENU_CALLBACK,
  );

  // Ajax callback to update block contents
  $items['user/%user/dashboard/update'] = array(
    'page callback'     => 'user_dashboard_update',
    'access callback'   => '_user_dashboard_access',
    'type'              => MENU_CALLBACK,
  );

  // Ajax callback to set default blocks
  $items['admin/dashboard/user_dashboard/set_default'] = array(
    'page callback'     => 'user_dashboard_set_default',
    'access arguments'  => array(USER_DASHBOARD_PERM_SET_DEFAULT),
    'type'              => MENU_CALLBACK,
  );

  return $items;
}

/**
 *  Implements hook_permission().
 */
function user_dashboard_permission() {
  return array(
    USER_DASHBOARD_PERM_SET_DEFAULT => array(
      'title'       => t('Set default blocks'),
      'description' => t('Grants access to set default UserDashboard blocks.'),
    ),
    USER_DASHBOARD_PERM_VIEW_ALL => array(
      'title'       => t("View all user's dashboards."),
      'description' => t("Grants access to view all user's dashboards."),
    ),
  );
}

/**
 *  Implements hook_init().
 */
function user_dashboard_init(){
  drupal_add_css(drupal_get_path('module', 'user_dashboard') . '/user_dashboard.css');
}

/**
 * Implements of hook_user_insert().
 *
 * Sets default user dashboard blocks if they are defined.
 */
function user_dashboard_user_insert(&$edit, $account, $category) {
  $default    = variable_get('user_dashboard_default_blocks', array());
  $available  = variable_get('user_dashboard_available_blocks', array());

  if (!empty($default)) {
    foreach ($default as $block) {
      // Make sure the block is still available
      if (in_array($block->module . '_' . $block->delta, $available)) {
        // Make sure the block still actually exists
        $data = db_select('block', 'b')
              ->fields('b')
              ->condition('theme',  $block->theme)
              ->condition('module', $block->module)
              ->condition('delta',  $block->delta)
              ->execute()
              ->fetchAssoc();

        if ($data) {
          db_merge('user_dashboard_block')
            ->key(array(
              'module'  => $block->module,
              'delta'   => $block->delta,
              'theme'   => $block->theme,
              'uid'     => $account->uid,
            ))
            ->fields(array(
              'status'  => $block->status,
              'weight'  => $block->weight,
              'region'  => $block->region,
              'pages'   => '',
              'uid'     => $account->uid,
            ))
            ->execute();
        }
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function user_dashboard_theme() {
  return array(
    'user_dashboard' => array(
      'render element' => 'element',
    ),
    'user_dashboard_page' => array(
      'render element' => 'element',
    ),
    'user_dashboard_region' => array(
      'render element' => 'element',
    ),
    'user_dashboard_disabled_blocks' => array(
      'variables' => array('blocks' => NULL),
    ),
    'user_dashboard_disabled_block' => array(
      'variables' => array('block' => NULL),
    ),
    'user_dashboard_admin_display_form' => array(
      // When building the form for configuring dashboard blocks, reuse the
      // Block module's template for the main block configuration form.
      'template' => 'block-admin-display-form',
      'path' => drupal_get_path('module', 'block'),
      'file' => 'block.admin.inc',
      'render element' => 'form',
    ),
    'user_dashboard_block_function_items' => array(
      'template' => 'user_dashboard_block',
      'path' => drupal_get_path('module', 'block'),
      'file' => 'block.admin.inc',
      'variables' => array('items' => NULL),
    ),
  );
}

/**
 * Implements hook_block_list_alter().
 *
 * Skip rendering dashboard blocks when not on the dashboard page itself. This
 * prevents expensive dashboard blocks from causing performance issues on pages
 * where they will never be displayed.
 */
function user_dashboard_block_list_alter(&$blocks) {
  if (!_user_dashboard_visible()) {
    foreach ($blocks as $key => $block) {
      if (in_array($block->region, _user_dashboard_regions())) {
        unset($blocks[$key]);
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function user_dashboard_form_block_admin_display_form_alter(&$form, &$form_state, $form_id) {
  // Hide dashboard regions (and any blocks placed within them) from the block
  // administration form and from the options list on that form. This
  // function is called for both the dashboard block configuration form and the
  // standard block configuration form so that both forms can share the same
  // constructor. As a result the form_id must be checked.
  if ($form_id != 'dashboard_admin_display_form') {
    $dashboard_regions = _user_dashboard_region_descriptions();
    $form['block_regions']['#value'] = array_diff_key($form['block_regions']['#value'], $dashboard_regions);
    foreach (element_children($form['blocks']) as $i) {
      $block = &$form['blocks'][$i];
      if (isset($block['region']['#default_value']) && isset($dashboard_regions[$block['region']['#default_value']]) && $block['region']['#default_value'] != 'dashboard_inactive') {
        $block['#access'] = FALSE;
      }
      elseif (isset($block['region']['#options'])) {
        $block['region']['#options'] = array_diff_key($block['region']['#options'], $dashboard_regions);
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function user_dashboard_form_block_admin_configure_alter(&$form, &$form_state) {
  global $theme_key;
  drupal_theme_initialize();
  // Hide the dashboard regions from the region select list on the block
  // configuration form, for all themes except the current theme (since the
  // other themes do not display the dashboard).
  // @todo This assumes the current page is being displayed using the same
  //   theme that the dashboard is displayed in.
  $dashboard_regions = _user_dashboard_region_descriptions();
  foreach (element_children($form['regions']) as $region_name) {
    $region = &$form['regions'][$region_name];
    if ($region_name != $theme_key && isset($region['#options'])) {
      $region['#options'] = array_diff_key($region['#options'], $dashboard_regions);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function user_dashboard_form_block_add_block_form_alter(&$form, &$form_state) {
  user_dashboard_form_block_admin_configure_alter($form, $form_state);
}

/**
 * Implements hook_page_build().
 *
 * Display dashboard blocks in the main content region.
 */
function user_dashboard_page_build(&$page) {
  if (_user_dashboard_visible()) {
    $settings = array(
      'user_dashboard' => array(
        'set_default_blocks_access' => (int) user_access('set default user_dashboard blocks'),
        'default_blocks_callback'   => url('admin/dashboard/user_dashboard/set_default'),
      ),
    );

    drupal_add_js($settings, array('type' => 'setting'));

     global $theme_key, $user;

    if ($user->uid > 0) {
    // Set weight = 1 to ensure that this gets added after the core dashboard's JS
        //drupal_add_js(drupal_get_path('module', 'user_dashboard') . '/js/jquery.ui.touch-punch.js', array('weight' => 99));
        drupal_add_js(drupal_get_path('module', 'user_dashboard') . '/js/user_dashboard.js', array('weight' => 100));

    }


    $available_blocks = variable_get('user_dashboard_available_blocks', array());

    // Load user dashboard blocks
    $query = db_select('user_dashboard_block', 'b');
    $result = $query
      ->fields('b')
      ->condition('b.theme', $theme_key)
      ->condition('b.status', 1)
      ->condition('b.uid', (int) arg(1))
      ->orderBy('b.region')
      ->orderBy('b.weight')
      ->orderBy('b.module')
      ->addTag('block_load')
      ->addTag('translatable')
      ->execute();

    $block_info = $result->fetchAllAssoc('bid');
    // Allow modules to modify the block list.
    drupal_alter('block_list', $block_info);

    $user_blocks = array();
    foreach ($block_info as $b) {
      // Ensure that this is still a valid block, otherwise remove it and alert the user
      $data = db_select('block', 'b')
              ->fields('b')
              ->condition('theme',  $b->theme)
              ->condition('module', $b->module)
              ->condition('delta',  $b->delta)
              ->execute()
              ->fetchAssoc();

      if (!$data || !in_array($b->module . '_' . $b->delta, $available_blocks)) {
        drupal_set_message(t('Block !delta provided by module !module is no longer available and has been removed from your dashboard.', array('!delta' => '<em>' . $b->delta . '</em>', '!module' => '<em>' . $b->module . '</em>')), 'warning');

        db_delete('user_dashboard_block')
          ->condition('theme',  $b->theme)
          ->condition('module', $b->module)
          ->condition('delta',  $b->delta)
          ->condition('uid',    $user->uid)
          ->execute();
      }
      else {
        $user_blocks[$b->region][$b->module . '_' . $b->delta] = $b;
      }
    }

    foreach ($user_blocks as $key => $r) {
      if ($list = _block_render_blocks($r)) {
        if (!isset($page[$key])) {
          $page[$key] = array();
        }

        $page[$key] += _block_get_renderable_array($list);
      }
    }

    $block_info = array();

    // Create a wrapper for the dashboard itself, then insert each dashboard
    // region into it.
    $page['content']['user_dashboard'] = array('#theme_wrappers' => array('user_dashboard'));
    foreach (_user_dashboard_regions() as $region) {
      // Insert regions even when they are empty, so that they will be
      // displayed when the dashboard is being configured.
      $page['content']['user_dashboard'][$region] = !empty($page[$region]) ? $page[$region] : array();
      $page['content']['user_dashboard'][$region]['#dashboard_region'] = $region;
      // Allow each dashboard region to be themed differently, or fall back on
      // the generic theme wrapper function for dashboard regions.
      $page['content']['user_dashboard'][$region]['#theme_wrappers'][] = array($region, 'user_dashboard_region');

      // Allow modules to alter the region
      drupal_alter('user_dashboard_region', $page['content']['user_dashboard'][$region]);

      unset($page[$region]);
      $blocks_found = array();
      foreach ($page['content']['user_dashboard'][$region] as $item) {
        if (isset($item['#theme_wrappers']) && is_array($item['#theme_wrappers']) && in_array('block', $item['#theme_wrappers'])) {
          // If this item is a block, ensure it has a subject.
          if (empty($item['#block']->subject)) {
            // Locally cache info data for the object for all blocks, in case
            // we find a block similarly missing title from the same module.
            if (!isset($block_info[$item['#block']->module])) {
              $block_info[$item['#block']->module] = module_invoke($item['#block']->module, 'block_info');
            }
            $item['#block']->subject = $block_info[$item['#block']->module][$item['#block']->delta]['info'];
          }
          $blocks_found[$item['#block']->module . '_' . $item['#block']->delta] = TRUE;
        }
      }

      // Find blocks which were not yet displayed on the page (were empty), and
      // add placeholder items in their place for rendering.
      $block_list = db_select('user_dashboard_block')
        ->condition('theme', $theme_key)
        ->condition('status', 1)
        ->condition('region', $region)
        ->condition('uid', (int) arg(1))
        ->fields('user_dashboard_block')
        ->orderBy('weight')
        ->execute();
      foreach ($block_list as $block) {
        if (!isset($blocks_found[$block->module . '_' . $block->delta])) {
          $block->enabled = $block->page_match = TRUE;
          $block->content = array('#markup' => '<div class="dashboard-block-empty">(empty)</div>');
          if (!isset($block_info[$block->module])) {
            $block_info[$block->module] = module_invoke($block->module, 'block_info');
          }
          $block->subject = t('@title', array('@title' => $block_info[$block->module][$block->delta]['info']));
          $block_render = array($block->module . '_' . $block->delta => $block);
          $build = _block_get_renderable_array($block_render);
          $page['content']['user_dashboard'][$block->region][] = $build;
        }
      }
    }
  }
}

/**
 * Implements hook_system_info_alter().
 *
 * Add regions to each theme to store the dashboard blocks.
 */
function user_dashboard_system_info_alter(&$info, $file, $type) {
  if ($type == 'theme') {
    // Add the dashboard regions (the "inactive" region should always appear
    // last in the list, for usability reasons).
    $info['regions'] += _user_dashboard_region_descriptions();
    // Indicate that these regions are intended to be displayed whenever the
    // dashboard is displayed in an overlay. This information is provided for
    // any module that might need to use it, not just the core Overlay module.
    $info['overlay_regions'] = !empty($info['overlay_regions']) ? array_merge($info['overlay_regions'], _user_dashboard_regions()) : _user_dashboard_regions();
  }
}

/************************************************************************************
 *                  MODULE HOOKS
 ***********************************************************************************/

/**
 * Implements hook_user_dashboard_regions().
 */
function user_dashboard_user_dashboard_regions() {
  return array(
    'user_dashboard_column1'  => 'Dashboard (column1)',
    'user_dashboard_column2'  => 'Dashboard (column2)',
    'user_dashboard_column3'  => 'Dashboard (column3)',
    'user_dashboard_column4'  => 'Dashboard (column4)',
    'user_dashboard_column5'  => 'Dashboard (column5)',
    'user_dashboard_column6'  => 'Dashboard (column6)',
    'user_dashboard_column7'  => 'Dashboard (column7)',
    'user_dashboard_column8'  => 'Dashboard (column8)',
    'user_dashboard_column9'  => 'Dashboard (column9)',
    'user_dashboard_column10' => 'Dashboard (column10)',
    'user_dashboard_column11' => 'Dashboard (column11)',
    'user_dashboard_column12' => 'Dashboard (column12)',
    'user_dashboard_column13' => 'Dashboard (column13)',
    'user_dashboard_column14' => 'Dashboard (column14)',
    'user_dashboard_column15' => 'Dashboard (column15)',
    'user_dashboard_column16' => 'Dashboard (column16)',
    'user_dashboard_column17' => 'Dashboard (column17)',
    'user_dashboard_column18' => 'Dashboard (column18)',
  );
}

/************************************************************************************
 *                  CALLBACKS
 ***********************************************************************************/

 /**
  * Shortcut to redirect users to their own dashboard.
  */
 function user_dashboard_page_redirect() {
   global $user;
   drupal_goto('user/' . $user->uid . '/dashboard');
 }

/**
 * Dashboard page callback.
 */
function user_dashboard_page($launch_customize = TRUE) {
  $js_settings = array(
    'dashboard' => array(
      'drawer' => url('user/' . arg(1) . '/dashboard/drawer'),
      'blockContent' => url('user/' . arg(1) . '/dashboard/block-content'),
      'updatePath' => url('user/' . arg(1) . '/dashboard/update'),
      'formToken' => drupal_get_token('user-dashboard-update'),
      'launchCustomize' => $launch_customize,
      'dashboard' => url('user/' . arg(1) . '/dashboard'),
      'emptyBlockText' => t('(empty)'),
      'emptyRegionTextInactive' => t('This dashboard region is empty. Click <em>Customize dashboard</em> to add blocks to it.'),
      'emptyRegionTextActive' => t('DRAG HERE'),
    ),
  );
  $build = array(
    '#theme' => 'user_dashboard_page',
    '#message' => t('To customize the dashboard page, move blocks to the dashboard regions on the <a href="@dashboard">Dashboard administration page</a>, or enable JavaScript on this page to use the drag-and-drop interface.', array('@dashboard' => url('admin/dashboard/configure'))),
    '#access' => 1,
    '#attached' => array(
      'js' => array(
        drupal_get_path('module', 'dashboard') . '/dashboard.js',
        array('data' => $js_settings, 'type' => 'setting'),
      ),
      'library' => array(array('system', 'ui.sortable')),
    ),
  );

  return $build;
}

/**
 * AJAX callback to show disabled blocks in the dashboard customization mode.
 */
function user_dashboard_show_disabled() {
  global $theme_key;

  $available = variable_get('user_dashboard_available_blocks', array());

  $user_blocks = db_select('user_dashboard_block')
    ->condition('theme', $theme_key)
    ->condition('status', 1)
    ->condition('uid', (int) arg(1))
    ->fields('user_dashboard_block')
    ->execute();

  $u_blocks = array();

  foreach ($user_blocks as $item) {
    unset($available[$item->module . '_' . $item->delta]);
  }

  // Blocks are not necessarily initialized at this point.
  $blocks = _block_rehash();

  foreach ($blocks as $key => $block) {
    $id = $block['module'] . '_' . $block['delta'];
    if (!isset($available[$id]) || !$available[$id]) {
      unset($blocks[$key]);
    }
  }

  // Theme the output and end the page request.
  print theme('user_dashboard_disabled_blocks', array('blocks' => $blocks));
  drupal_exit();
}

/**
 * Module settings page.
 */
function user_dashboard_settings() {
  global $theme_key;

  drupal_theme_initialize();
  module_load_include('inc', 'block', 'block.admin');

  $blocks = array();
  foreach (block_admin_display_prepare_blocks($theme_key) as $block) {
    $blocks[$block['module'] . '_' . $block['delta']] = $block['info'];
  }
  $form = array();

  $form['user_dashboard_available_blocks'] = array(
    '#default_value'  => variable_get('user_dashboard_available_blocks', array()),
    '#description'    => t('Choose blocks that can be used on the user dashboard pages.'),
    '#options'        => $blocks,
    '#title'          => t('Available blocks'),
    '#type'           => 'checkboxes',
  );

  return system_settings_form($form);
}

/**
 * Removing default regions
 */
function user_dashboard_user_dashboard_regions_alter(&$regions) {
	unset($regions['user_dashboard_main']);
	unset($regions['user_dashboard_sidebar']);
	unset($regions['user_dashboard_footer']);
}

/**
 * AJAX callback for user/%user/dashboard/block-content/%/%
 */
function user_dashboard_show_block_content($module, $delta) {
  dashboard_show_block_content($module, $delta);
}

/**
 * AJAX callback for user/%user/dashboard/update
 *
 * Set the new weight of each region according to the drag-and-drop order.
 */
function user_dashboard_update() {
  drupal_theme_initialize();
  global $theme_key;
  global $user;
  $unsaved = array();
  // Check the form token to make sure we have a valid request.
  if (!empty($_REQUEST['form_token']) && drupal_valid_token($_REQUEST['form_token'], 'user-dashboard-update')) {
    parse_str($_REQUEST['regions'], $regions);

    // Get a list of enabled modules with values that matches the block_string from the block id.
    $module_list = module_list();
    foreach ($module_list as $module) {
      $module_map[$module] = str_replace('_', '-', $module);
    }
    foreach ($regions as $region_name => $blocks) {
      foreach ($blocks as $weight => $block_string) {
        // Replaces any malformed module name containing more than one word
        foreach ($module_map as $module_name => $module) {
          $block_string = str_replace($module, $module_name, $block_string);
        }

        // Parse the query string to determine the block's module and delta.
        preg_match('/block-([^-]+)-(.+)/', $block_string, $matches);
        $block = new stdClass();
        $block->module = $matches[1];
        $block->delta = $matches[2];
        $block->region = $region_name;
        $block->weight = $weight;
        $block->status = 1;

        if ($block->region !== 'disabled_blocks') {
          // Certain block module/delta combinations (like from Views blocks) may come in with an incorrect
          // delta, where '-' are used in place of '_', so we need to ensure we're getting the right delta
          // by querying the {blocks} table
          $delta_obj = db_query("SELECT delta FROM {block} WHERE module = '" . $block->module . "' AND REPLACE(REPLACE(delta, '-', ''), '_', '') = '" . preg_replace('/[-_]/', '', $block->delta) . "' LIMIT 1", array(
            ':module' => $block->module,
            ':delta'  => preg_replace('/[-_]/', '', $block->delta),
          ))->fetchObject();

          $block->delta = $delta_obj->delta;

         $existing = db_query("SELECT ub.bid FROM {user_dashboard_block} ub WHERE ub.region = :region AND ub.uid = :uid", array(':region' => $block->region, ':uid' => $user->uid))->fetchField();
          if (!is_numeric($existing)) {
            db_merge('user_dashboard_block')
              ->key(array(
                'module'  => $block->module,
                'delta'   => $block->delta,
                'theme'   => $theme_key,
                'uid'     => (int) arg(1),
              ))
              ->fields(array(
                'status'  => $block->status,
                'weight'  => $block->weight,
                'region'  => $block->region,
                'pages'   => '',
              ))
              ->execute();
          } else {
            if ($_REQUEST['current'] != '' && $block->delta == $_REQUEST['current']) {
              $unsaved[$existing] = $_REQUEST['current'];
            }
          }
        }
        else {
          db_delete('user_dashboard_block')
            ->condition('uid', (int) arg(1))
            ->condition('module', $block->module)
            ->condition('delta', $block->delta)
            ->execute();
        }
      }
    }
    drupal_set_message(t('The configuration options have been saved.'), 'status', FALSE);
  }
  array_unique($unsaved);
  if (!empty($unsaved)) {
    print drupal_json_output($unsaved);
  }
  drupal_exit();
}

/**
 * AJAX callback for admin/dashboard/user_dashboard/set_default
 *
 * Set the default blocks that will be initialized for new user registrations.
 */
function user_dashboard_set_default() {
  // Check the form token to make sure we have a valid request.
  if (!empty($_REQUEST['form_token']) && drupal_valid_token($_REQUEST['form_token'], 'user-dashboard-update')) {
    $default_blocks = array();

    parse_str($_REQUEST['regions'], $regions);
    foreach ($regions as $region_name => $blocks) {
      foreach ($blocks as $weight => $block_string) {
        // Parse the query string to determine the block's module and delta.
        preg_match('/block-([^-]+)-(.+)/', $block_string, $matches);
        $block = new stdClass();
        $block->module  = $matches[1];
        $block->delta   = $matches[2];
        $block->region  = $region_name;
        $block->weight  = $weight;
        $block->status  = 1;
        $block->theme   = variable_get('theme_default', 'garland');

        if ($block->region !== 'disabled_blocks') {
          // Certain block module/delta combinations (like from Views blocks) may come in with an incorrect
          // delta, where '-' are used in place of '_', so we need to ensure we're getting the right delta
          // by querying the {blocks} table
          $delta_obj = db_query("SELECT delta FROM {block} WHERE module = '" . $block->module . "' AND REPLACE(REPLACE(delta, '-', ''), '_', '') = '" . preg_replace('/[-_]/', '', $block->delta) . "' LIMIT 1", array(
            ':module' => $block->module,
            ':delta'  => preg_replace('/[-_]/', '', $block->delta),
          ))->fetchObject();

          $block->delta = $delta_obj->delta;

          $default_blocks[] = $block;
        }
      }
    }

    variable_set('user_dashboard_default_blocks', $default_blocks);

    drupal_set_message(t('Default blocks have been set.'), 'status', FALSE);

    echo drupal_json_encode(array('messages' => theme('status_messages')));
  }

  drupal_exit();
}

/************************************************************************************
 *                  THEMING
 ***********************************************************************************/

/**
 * Returns HTML for the entire dashboard.
 */
function theme_user_dashboard($variables) {
  global $user;
  extract($variables);
  if ($user->uid > 0) {
      drupal_add_css(drupal_get_path('module', 'dashboard') . '/dashboard.css');
      // Drupal_add_js(drupal_get_path('module','user_dashboard') . '/js/custom.js');
      $form = drupal_get_form('user_dashboard_image_content_form');
      $imageurl = '';

      $fid = user_dashboard_get_image();
      if (isset($fid) && $fid > 0) {
        $file = file_load($fid);
        if (!empty($file)) {
          $imageurl = file_create_url($file->uri);
        }
      }

      $output = '<div id="dashboard" class="clearfix user-dashboard customize-mode customize-inactive">';
      if ($imageurl != '') {
        $output .= '<div class="background-image displaynone"><img src="' . $imageurl . '"></div>';
      }
      $output .= '<div class="all-regions displaynone"><div class="title">Customize Your Home Page</div>' . $element['#children'] . '</div>';
      $output .= '</div>';

      $output .= '<div class="displaynone">' . drupal_render($form) . '</div>';
      $output .= '<div class="loading"><img src="' . base_path() . drupal_get_path('theme', 'mph_theme') . '/images/loading.gif"></div>';

      return $output;
  }
}

/**
 * Returns HTML for the non-customizable part of the dashboard page.
 */
function theme_user_dashboard_page($variables) {
  // We only return a simple help message, since the actual content of the page
  // will be populated via the dashboard regions in dashboard_page_build();
  return '<div class="customize-dashboard js-hide">' . $variables['element']['#message'] . '</div>';
}

/**
 * Returns HTML for a generic dashboard region.
 */
function theme_user_dashboard_region($variables) {
  extract($variables);

  $output = '
              <div id="' . $element['#dashboard_region'] . '" class="user-dashboard-region">
                <div class="region clearfix">
                  ' . $element['#children'] . '
                </div>
              </div>
            ';

  return $output;
}

/**
 * Returns HTML for a set of disabled blocks, for display in dashboard customization mode.
 */
function theme_user_dashboard_disabled_blocks($variables) {
  extract($variables);
  $output = '';
  // $output .= '<div class="canvas-content"><p>' . t('Drag and drop these blocks to the columns below. Changes are automatically saved. More options are available on the UserDashboard <a href="@dashboard-url">configuration page</a>.', array('@dashboard-url' => url('admin/dashboard/user_dashboard/settings'))) . '</p>';
  $output .= '<div id="disabled-blocks"><div class="title">Drag & Drop Icon On Grid</div><div class="region disabled-blocks clearfix">';
  foreach ($blocks as $block) {
    $output .= theme('user_dashboard_disabled_block', array('block' => $block));
  }
  $output .= '<div class="clearfix"></div>';
  $output .= '</div></div></div>';
  return $output;
}

/**
 * Returns HTML for a disabled block, for display in dashboard customization mode.
 */
function theme_user_dashboard_disabled_block($variables) {
  extract($variables);
  $output = "";
  if (isset($block)) {

    $block_content = module_invoke('block', 'block_view', $block['delta']);

    $output .= '<div id="block-' . $block['module'] . '-' . $block['delta']
    . '" class="disabled-block block block-' . $block['module'] . '-' . $block['delta']
    . ' module-' . $block['module'] . ' delta-' . $block['delta'] . '">'
    . '<div class="content"> ' . strip_tags(render($block_content['content']), '<img>') . '</div>'
    . '</div>';
  }
  return $output;
}

/************************************************************************************
 *                  INTERNAL
 ***********************************************************************************/

/**
 * Checks whether the current user is allowed to access the dashboard.
 */
function _user_dashboard_access($account = NULL) {
  global $user;

  if (is_null($account)) {
    $account = $user;
  }

  if (!$user->uid || ($account->uid != $user->uid && !user_access(USER_DASHBOARD_PERM_VIEW_ALL))) {
    return FALSE;
  }

  return TRUE;
}

/**
 * Check if we are on the user dashboard page.
 */
function _user_dashboard_visible() {
  return preg_match('/^user\/[0-9]{0,11}\/dashboard$/', implode('/', arg()));
}

/**
 * Return an array of dashboard region names.
 */
function _user_dashboard_regions() {
  $regions = &drupal_static(__FUNCTION__);
  if (!isset($regions)) {
    $regions = array_keys(_user_dashboard_region_descriptions());
  }
  return $regions;
}

/**
 * Return an array of dashboard region descriptions, keyed by region name.
 */
function _user_dashboard_region_descriptions() {
  $regions = module_invoke_all('user_dashboard_regions');
  drupal_alter('user_dashboard_regions', $regions);
  return $regions;
}

/**
 * Form for uploading image in user dashboard.
 */
function user_dashboard_image_content_form($form, &$form_state)
{
    $fid = user_dashboard_get_image();

    $form['backgroundimage_image'] = array(
      '#type' => 'managed_file',
      '#name' => 'backgroundimage_image',
      '#title' => t('Upload Image'),
      '#default_value' => (isset($fid) && $fid > 0) ? $fid : '',
      '#description' => t("Upload an image for the background. Allowed extensions: gif png jpg jpeg"),
      '#required' => FALSE,
      '#upload_location' => 'public://backgroundimage/',
      '#upload_validators' => array(
        'file_validate_extensions' => array('gif png jpg jpeg'),
        // Pass the maximum file size in bytes
        'file_validate_size' => array(25 * 1024 * 1024),
      ),
    );


     // Submit Button.
      $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Save'),
      );

	return $form;
}

/**
 * Implements hook_form_submit().
 */
function user_dashboard_image_content_form_submit($form, &$form_state) {
  global $user;
    if ($form_state['values']['backgroundimage_image'] == 0) {
        $fid = user_dashboard_get_image();
        if (isset($fid) && $fid > 0) {
            $delete_file = file_load($fid);
            file_delete($delete_file);
            db_query('DELETE FROM {user_dashboard_block_image} WHERE fid = ' . $fid . '');
        }
    }


  if ($form_state['values']['backgroundimage_image'] != 0) {
    $fid = user_dashboard_get_image();
    if (isset($fid) && $fid > 0) {
        $delete_file = file_load($fid);
        file_delete($delete_file);
        db_query('DELETE FROM {user_dashboard_block_image} WHERE fid = ' . $fid . '');
    }


    $file = file_load($form_state['values']['backgroundimage_image']);
    $file->status = FILE_STATUS_PERMANENT;
    file_save($file);
    file_usage_add($file, 'user_dashboard', 'dashboard_image', 1);

    db_insert('user_dashboard_block_image')
        ->fields(array(
            'fid' => $file->fid,
            'uid' => $user->uid,
        ))
    ->execute();

  }

}

/**
 * Function get dashboard image of user.
 */
function user_dashboard_get_image() {
    global $user;
    $fid = 0;
    if ($user->uid > 0) {
        $query = db_select('user_dashboard_block_image', 'u');
        $query->fields('u', array('fid'));
        $query->condition('uid', $user->uid);
        $fid = $query->execute()->fetchField();

        return isset($fid) ? $fid : '';
    }
}

/**
 * Function checks dashboard items of user.
 */
function user_dashboard_check_dashboard_items() {

    global $theme_key, $user;
    $count = 0;
    $query = db_select('user_dashboard_block', 'b');
    $result = $query
      ->fields('b')
      ->condition('b.theme', $theme_key)
      ->condition('b.status', 1)
      ->condition('b.uid', (int) $user->uid)
      ->orderBy('b.region')
      ->orderBy('b.weight')
      ->orderBy('b.module')
      ->addTag('block_load')
      ->execute();


    $block_info = $result->fetchAllAssoc('bid');
    if (!empty($block_info)) {
        $count = count($block_info);
    }
    return $count;

}

/**
 * Function get dashboard info.
 */
function user_dashboard_block_info()
{
	$blocks['user_dashboard_front_block'] = array(
			'info' => t('User dashboard image block.'),
			'cache' => DRUPAL_NO_CACHE,
	);

	return $blocks;
}

/**
 * Function get dashboard block view of particular user.
 */
function user_dashboard_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'user_dashboard_front_block':
      if (user_access('access content')) { // Good idea to check user perms here
        $block['subject'] = t('User dashboard image');
        $block['content'] = user_dashboard_block_function_items();
      }
      break;
  }
  return $block;
}

/**
 * Function get dashboard available blocks.
 */
function user_dashboard_block_function_items() {
  global $theme_key, $user;
  $output = '';
  $page = array();

  if ($user->uid > 0) {

    $available_blocks = variable_get('user_dashboard_available_blocks', array());
    $query = db_select('user_dashboard_block', 'b');
    $result = $query
      ->fields('b')
      ->condition('b.theme', $theme_key)
      ->condition('b.status', 1)
      ->condition('b.uid', (int) $user->uid)
      ->orderBy('b.region')
      ->orderBy('b.weight')
      ->orderBy('b.module')
      ->addTag('block_load')
      ->execute();


    $block_info = $result->fetchAllAssoc('bid');

    // Drupal_alter('block_list', $block_info);
    $user_blocks = array();
    foreach ($block_info as $b) {
      // Ensure that this is still a valid block, otherwise remove it and alert the user
      $data = db_select('block', 'b')
              ->fields('b')
              ->condition('theme',  $b->theme)
              ->condition('module', $b->module)
              ->condition('delta',  $b->delta)
              ->execute()
              ->fetchAssoc();

      if (!$data || !in_array($b->module . '_' . $b->delta, $available_blocks)) {
        db_delete('user_dashboard_block')
          ->condition('theme',  $b->theme)
          ->condition('module', $b->module)
          ->condition('delta',  $b->delta)
          ->condition('uid',    $user->uid)
          ->execute();
      }
      else {
        $user_blocks[$b->region][$b->module . '_' . $b->delta] = $b;
      }
    }


    foreach ($user_blocks as $key => $r) {
      if ($list = _block_render_blocks($r)) {
        if (!isset($page[$key])) {
          $page[$key] = array();
        }

        $page[$key] += _block_get_renderable_array($list);
      }
    }

      $imageurl = '';

      $fid = user_dashboard_get_image();
      if (isset($fid) && $fid > 0) {
        $file = file_load($fid);
        if (!empty($file)) {
          $imageurl = file_create_url($file->uri);
        }
      }
  $class = '';
  $output = '<div id="dashboard" class="clearfix user-dashboard user-dashboard-homepage">';
  if ($imageurl != '') {
    $output .= '<div class="background-image"><img src="' . $imageurl . '"></div>';
  } else {
    $class = 'dashboard-no-image';
  }
  $output .= '<div class="outer-regions"> <div class="all-regions ' . $class . '">';
    $blocks_found = array();
    foreach (_user_dashboard_regions() as $region) {
        $render_content = '';
        if (!empty($page[$region])) {
            foreach ($page[$region] as $item) {
                if (isset($item['#theme_wrappers']) && is_array($item['#theme_wrappers']) && in_array('block', $item['#theme_wrappers'])) {
                    $block_content = module_invoke($item['#block']->module, 'block_view', $item['#block']->delta);
                    $render_content = render($block_content['content']);
                    break;
                }
            }
        }
        $output .= '<div id="' . $region . '" class="user-dashboard-region"><div class="region clearfix">' . $render_content . '</div></div>';
    }
    $output .= '</div></div></div>';
  }
  return $output;
}
